name: Schedule Database Update

on:
  schedule:
    # Runs every day at 1 PM UTC, which is midnight in Sydney (UTC+11 during daylight saving)
    - cron: "0 13 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-database:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run database update
        run: npm run update-db
